apiVersion: apps/v1
kind: Deployment
metadata:
  name: laundry
  labels:
    app: laundry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laundry
  template:
    metadata:
      labels:
        app: laundry
    spec:
      containers:
        - name: laundry
          image: clothrentalt.azurecr.io/laundry
          ports:
            - containerPort: 8080